### ISSUE TITLE
Tag vocabularies

### ISSUE THREAD

**Issue by hvwaldow** [ckan/ckanext-scheming#117]
Scheming currently does not handle using tag vocabularies in schemas. I am aware that `choices` targets  selection from a given list. However, using tag vocabs for that purpose would allow creating, deleting and modifying the possible values programmatically via the remote API. This is very useful for uses-cases where scheming is used to create and maintain a number of different interfaces for different user-groups and where the list of potential choices for different fields might change frequently (e.g. due to user feedback). 

Here is an implementation: https://github.com/ckan/ckanext-scheming/pull/116

**Comment by wardi** [comment]
This can now be implemented on top of the changes in #131. You just need to define a helper that returns the vocabulary as the choice list (and cache it if you like). #132 implements choices based on a datastore table, which you might find performs better than tag vocabulary queries
