### ISSUE TITLE
Notes fields being duplicated

### ISSUE THREAD

**Issue by corebits** [ckan/ckanext-scheming#119]
Running Ckan 2.3.1

Attempting to update to scheming release-1.0.0, however I am seeing my description field being duplicated below tags. 

The issue (for me) appears after this commit [8e83c0e](https://github.com/ckan/ckanext-scheming/commit/8e83c0ecf9a5f02e16fb59b0c2d856de650899a3)

If I revert to the previous commit [e4941f5](https://github.com/ckan/ckanext-scheming/commit/e4941f50b81dda324acb102b9462ba3046ede940) the duplication goes away.

e4941f5
![scheming error 1](https://cloud.githubusercontent.com/assets/2831763/12800227/bef446f0-ca90-11e5-815a-2321d382e513.JPG)

8e83c0e
![scheming error 2](https://cloud.githubusercontent.com/assets/2831763/12800228/bf110dbc-ca90-11e5-8f0d-87ac27184415.JPG)

**Comment by wardi** [comment]
```
21:34 < corebits> wardi: Sorry :(  I got way ahead of myself on this one.
21:35 < corebits> it is something in our theme, I will dig at it more tomorrow.
```
