### ISSUE TITLE
After Scheming implementation, dataset_count wont display correct number of available dataset(s) on frontpage

### ISSUE THREAD

**Issue by carbowizzy** [ckan/ckanext-scheming#137]
After Scheming implementation, dataset_count wont display correct number of available dataset(s) on frontpage and /stats. However, it displays the old dataset(s) but not newly added datasets.

I have tried fixing this problem but am abit concerned not to scatter things beyond repair. any reason for this  ?

**Comment by carbowizzy** [comment]
Problem solved : Data access was set to private

**Comment by NicolaiMogensen** [comment]
This issue should probably be closed then.
