### ISSUE TITLE
Additional metadata fields not taking effect

### ISSUE THREAD

**Issue by carbowizzy** [ckan/ckanext-scheming#149]
Hi,

- Could you please help with this issue. I added new metadata fields to my scheming dataset.json and reloaded it but won't appear on the page.

- It appears to me that the **dataset.json** name is already registered somewhere because when i deleted the content of **dataset.json** and reloaded i still, i still have my portal working fine.

Thank you

**Comment by carbowizzy** [comment]
Fixed;
 I had to link to url on http://localhost:5000/dataset.json instead of ckanext.scheming:dataset.json

**Comment by wardi** [comment]
@carbowizzy glad you got it working!
