### ISSUE TITLE
ckantoolkit

### ISSUE THREAD

**Issue by m-sinclair** [ckan/ckanext-scheming#152]
In the plugin.py file shouldnt
`from ckantoolkit import (`
be
`from ckan.plugins.toolkit`?

`ImportError: No module named ckantoolkit`

**Comment by wardi** [comment]
ckanext-scheming uses ckantoolkit https://github.com/ckan/ckanext-scheming/blob/master/requirements.txt#L2 to be able to support a wide range of ckan versions.

If you've got a new enough ckan then importing from ckantoolkit should work exactly the same as importing from `ckan.plugins.toolkit`.
