### ISSUE TITLE
Hyperlinking on fields

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckanext-scheming#153]
I'd like to add in optional hyperlinking on each metadata field on package display, so that if the schema says hyperlinking is on, the field displays with <a href="/dataset?[field]=[value from this package]">[value from this package]</a>

What do you think? Would this be accepted (not keen on maintaining a fork)

**Comment by wardi** [comment]
isn't that just an override for a display snippet? Am I missing something?

**Comment by mattfullerton** [comment]
I'm so sorry, I'd no idea the extension was so sophisticated as to allow that. I'll quietly close this now and go read the docs properly...

**Comment by wardi** [comment]
no worries! the docs are quite thin. If you can't figure it out just post an example of exactly what you're trying to do and I'm happy to help
