### ISSUE TITLE
[Question] Exist a preset for dataset multiselect with search?

### ISSUE THREAD

**Issue by thenets** [ckan/ckanext-scheming#154]
Can I create a field to add dataset URLs related with my new schema type?

My problem:
I need to create a "Application" schema type. And my application use some datasets.
So I need to allow users to add datasets related with my "Application" package.

For example:
![image](https://cloud.githubusercontent.com/assets/2138276/26513050/d1096820-423f-11e7-8066-d06d6a2be9b1.png)

**Comment by wardi** [comment]
This doesn't exist but it should be easy to add with the right form snippet (and validator). This is something you can implement in your own extension too, it doesn't need to be in ckanext-scheming. The trickiest part is going to be providing some kind of in-line search or autocomplete to make it user-friendly.

Here's an example of an extension that adds a user select box as a scheming field: https://github.com/OpenGov-OpenData/ckanext-datasetpermissioning . There's no fancy searching or autocomplete but should get you started.

**Comment by thenets** [comment]
Thanks! I'll start with it next week. You help me again.
