### ISSUE TITLE
[Bug] Resource/groups/activity URLs doesn't support schema name.

### ISSUE THREAD

**Issue by thenets** [ckan/ckanext-scheming#157]
The scheming doesn't support the actions 'resource', 'groups', 'activity'.

These URL works ok:
http://localhost:5000/concurso/concurso-1
http://localhost:5000/dataset/concurso-1/resource/9a31c1ca-4b68-48c5-a1f1-668e5e5f01b1
http://localhost:5000/dataset/groups/concurso-1
http://localhost:5000/dataset/activity/concurso-1

But these URLs return error 404:
http://localhost:5000/concurso/concurso-1/resource/9a31c1ca-4b68-48c5-a1f1-668e5e5f01b1
http://localhost:5000/concurso/groups/concurso-1
http://localhost:5000/concurso/activity/concurso-1

**Comment by wardi** [comment]
scheming doesn't add the routes, that's part of the IDatasetForm handling in ckan. Would you care to open the issue there instead?

**Comment by thenets** [comment]
Yes! ^^
I'll open the issue later or tomorrow. Added to my backlog.
