### ISSUE TITLE
Custom fields can't be created from API

### ISSUE THREAD

**Issue by mouillerart** [ckan/ckanext-scheming#158]
Hello,

I made a custom schema with a "language" field for datasets. The field can be filled using the GUI and read with package_show, but when I try to create or update it using API (package_create / package_update), CKAN does not accept the field (although it accepts all standard CKAN fields).

Is it a missing feature, like automatically integrating a new scheme in package_dict ?

**Comment by tedstrauss** [comment]
Having exactly the same issue. 
I'm using `ckanapi` extension as API interface.

**Comment by wardi** [comment]
no, new fields get added to the API like the other fields. Can you post a small example schema that demonstrates the issue?

**Comment by tedstrauss** [comment]
Here is the schema "bids_meg": https://gist.github.com/tedstrauss/5d5e305faadcc22bf9fce7010a7be2e9
Here is the metadata being imported: https://gist.github.com/tedstrauss/dd8f0f4486e7a2be2842f8f27aced03b
Call to ckanapi:
`> ckanapi load datasets -I import_this_dataset.json -c /etc/ckan/default/development.ini`

The package is created on the CKAN instance, but none of the special fields of the schema are added. Do I need to specify the type in the JSON somewhere?

Here is the output on the command line:

```
/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
  sess._flush_warning("related attribute set")
1 [None] --- create None "abcdefghv1002e"

```

**Comment by wardi** [comment]
Yes, you need to use `"type": "bids_meg"` in your dataset or the default schema will apply instead of the one you defined.

**Comment by tedstrauss** [comment]
That worked! Thanks.
I was using `"dataset_type": "bids_meg"`
Now to get the same fields represented in LOD with DCAT: https://github.com/ckan/ckanext-dcat/issues/56
