### ISSUE TITLE
Installation section missing from the README.md

### ISSUE THREAD

**Issue by terchris** [ckan/ckanext-scheming#167]
Hi
There is no Installation description for this plugin.

**Comment by gavinpc-mindgrub** [comment]
@wardi, is this the correct procedure?

```sh
. /usr/lib/ckan/default/bin/activate
cd /usr/lib/ckan/default/src
pip install -e ”git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming”
cd ./ckanext-scheming
pip install -r /usr/lib/ckan/default/src/ckanext-scheming/requirements.txt
```

as indicated here: https://lists.okfn.org/pipermail/ckan-dev/2016-September/010312.html

**Comment by wardi** [comment]
That ought to work assuming the manifest.in file is set up properly, yes.
