### ISSUE TITLE
Custom schema packages not being indexed by Solr

### ISSUE THREAD

**Issue by tedstrauss** [ckan/ckanext-scheming#171]
I have created a custom dataset type using scheming, `bids_meg`: https://gist.github.com/tedstrauss/5d5e305faadcc22bf9fce7010a7be2e9

My Solr is running on Tomcat7. I added a couple lines to the schema.xml file:
```
<field name="bids_meg_type" type="string" indexed="true" stored="true" />
<field name="InstitutionName" type="textgen" indexed="true" stored="true" />
```
(The first line is meant to add the custom type itself. And the second line is just the first of 30+ fields within the type.)
I restart Tomcat7, and run the re-indexing command:
```
sudo service restart tomcat7
ckan search-index rebuild -r --config=/etc/ckan/default/development.ini
```

The re-indexing command runs fine, but no packages of type `bids_meg` are indexed.

At the `/datasets` page, no packages of type `bids_meg` are listed or returned from the search. 
At `/bids_meg`, the custom type are listed; is a change to the CKAN theme needed to include custom types on the main `/datasets` page? 

I've gone through similar issues on this repo, but still haven't solved this.

Does something need to be changed in `circle.yml` because I'm using Tomcat and not Catalina?

**Comment by wardi** [comment]
What's your http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-search-show-all-types setting? by default /dataset only shows dataset-type datasets

**Comment by tedstrauss** [comment]
I had no such setting in my config. 
Adding `ckan.search.show_all_types = true` fixed it right up.
Thanks for ongoing amazing support @wardi !
