### ISSUE TITLE
Support YAML as a schema format?

### ISSUE THREAD

**Issue by roll** [ckan/ckanext-scheming#172]
Hi,

I'm new to the CKAN scheming (and CKAN in overall). Just finished my first `dataset.json`. It was a great experience except for one thing - editing JSON manually. 

I'm wondering - could YAML be added as supported schema format? I think it provides faster and more human-friendly writing experience and very important ability to add comments. 

For example here I and @amercader use YAML to write JSON Schemas (and document it as the same time) - https://github.com/frictionlessdata/goodtables.io/blob/master/goodtablesio/schemas/validation-conf.yml

**Comment by wardi** [comment]
we do support yaml https://github.com/ckan/ckanext-scheming/blob/master/CHANGELOG.md#100 but this could be added to the readme to make it more obvious. I'd also be fine with converting the example schemas to yaml for maintainability and readability.

**Comment by roll** [comment]
@wardi 
Thanks
