### ISSUE TITLE
Error in schemas including tags and resources

### ISSUE THREAD

**Issue by sykelahtineni** [ckan/ckanext-scheming#193]
Hello!

We have installed the scheming extension in CKAN 2.6.1b and it seems to work perfectly excluding one specific case.

Saving the dataset doesn't work if both tags and resources are included in the same schema.

Steps for reproducing the possible bug:

1. Create the schema including tags and resources. For example, as follows.

{
  "scheming_version": 1,
  "dataset_type": "tag-string-test",
  "dataset_fields": [
    {
      "field_name": "title",
      "label": "Title",
      "preset": "title"
    },
    {
      "field_name": "name",
      "label": "URL",
      "preset": "dataset_slug"
    },
    {
      "field_name": "owner_org",
      "label": "Organization",
      "preset": "dataset_organization"
    },
    {
      "field_name": "tag_string",
      "label": "Keyword",
      "required": "true",
      "preset": "select",
      "choices": [
        {
	  "value": "keyword-a",
	  "label": "keyword-a"
	},
        {
          "value": "keyword-b",
          "label": "keyword-b"
        }
      ]
    }
  ],
 "resource_fields": [
    {
      "field_name": "url",
      "label": "Photo",
      "preset": "resource_url_upload",
      "upload_label": "Photo"
    }
  ]
}

2. Enable the schema to your CKAN instance.

3. Open the form at your.ckan.com/tag-string-test/new.

4. Fill the fields in both "Create dataset" and "Add data" pages.

5. Click "Finish".

6. CKAN returns Error 500 "Server Error - An internal server error occurred".

Saving the dataset works successfully if the field name tag_string is replaced with anything else or if the resource is left out.

We tried to trace the error with the help of logs but without success. Might be a bug related to saving the tags?

Best regards,

Ismo Lahtinen
Finnish Environment Institute (SYKE)

**Comment by wardi** [comment]
The only preset that works with `tag_string` is `tag_string_autocomplete` or similar.

If you'd like to add a controlled with the `select` preset use a differently named field, because `tag_string` is handled in a special way by CKAN
