### ISSUE TITLE
multiple_select or multiple_checkbox creates array on facet list

### ISSUE THREAD

**Issue by mystycs** [ckan/ckanext-scheming#195]
If I create a multiple_select or multipe_checkbox field in my dataset.json When I start selecting multiple values for a package and updating it, my facet list starts printing stuff in an array.

["turtles", "sea creatures"]

I created the custom fields using the scheming extension. and this particular field is multiple checkbox which has multi value.

See example below:
<img width="302" alt="screen shot 2018-09-13 at 4 55 18 pm" src="https://user-images.githubusercontent.com/3004566/45515327-d3f67080-b775-11e8-8cf5-5850cc197480.png">

I am also previewing my facet list in my extension using this below which works, but it prints as an array:
`facets_dict['descriptives'] = plugins.toolkit.('desc')
`

**Comment by mystycs** [comment]
how can i have it print these all separately like it would be if I just chose select and still counted/displayed them if clicked.

**Comment by wardi** [comment]
Until we get dynamic solr schemas in CKAN you have to edit your solr schema to tell solr that this field is `multiValued="true"`, and then you need to create a `before_index` plugin to pass the values as a list.

E.g. this is what we use for our "subject" field
1. solr schema https://github.com/open-data/ckanext-canada/blob/master/conf/solr/schema.xml#L152
2. before_index parse stored json https://github.com/open-data/ckanext-canada/blob/master/ckanext/canada/plugins.py#L463

That should be it

**Comment by mystycs** [comment]
So would I set name="subject" to name="descriptives" in this case in sold
schema?

**Comment by FrantisekPavlicek** [comment]
Hello, I'm now running into the same problem, but I can't get your fix to work. You've probably done a little work on your plugin since, so the reference to the line 463 is no longer useful. Could you please briefly show the code that I need to use in the `before_index` plugin? Is it just the line
`data_dict['subject'] = json.loads(data_dict.get('subject', '[]'))`
or is there anything else I'm missing?

Also I noticed, that if I use the `before_index` plugin, the webserver also wants me to use some other plugins, like `before_search`, `after_search` etc. Is there anything important I need to do within these plugins? If I use these, I'm then unable to rebuild my search index and I end up with this error.
`Indexing dataset 1/32021-03-31 19:50:30,526 ERROR [ckan.lib.search] Error while indexing dataset 71e8b63e-e08c-4c84-8d87-5c647fd68fbd: AttributeError("'ClevermapsPlugin' object has no attribute 'read'")`

Any help would be really appreciated.

**Comment by wardi** [comment]
@FrantisekPavlicek I've updated the links in my reply above, HTH

**Comment by FrantisekPavlicek** [comment]
@wardi I actually figured out before that this was the line I was looking for but it still somehow didn't work for me. Anyway after couple days of playing around, I finally got it to work. Thanks for your response and for this awesome plugin!

**Comment by frafra** [comment]
> Until we get dynamic solr schemas in CKAN you have to edit your solr schema

We have dynamic solr schemas, which can be altered via API. Should we address this issue differently?

**Comment by maxclac** [comment]
Dear @FrantisekPavlicek, I encountered the same problem as you. How did you manage to make it work?

**Comment by FrantisekPavlicek** [comment]
@maxclac In the end, I think I just ended up with adding the field to the solr schema with multivalued=true, like this:

**Comment by maxclac** [comment]
Thank you for the quick answer. 

I am still having an error message similar to what you had:

```
2023-03-08 16:04:50,245 | ERROR | [ckan.config.middleware.flask_app] | 'SchemingDatasetsPlugin' object has no attribute 'before_search'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/../../views/dataset.py", line 316, in search
    query = get_action(u'package_search')(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1835, in package_search
    data_dict = item.before_search(data_dict)
AttributeError: 'SchemingDatasetsPlugin' object has no attribute 'before_search'
```

I also cannot rebuild the index:
```
# ckan -c /etc/ckan/default/ckan.ini search-index rebuild
#############################
Indexing dataset 1/82023-03-08 16:08:40,011 | ERROR | [ckan.lib.search] | Error while indexing dataset b417cf4b-d3f2-420a-84d9-1fdfbba15ea2: AttributeError("'SchemingDatasetsPlugin' object has no attribute 'read'")
'SchemingDatasetsPlugin' object has no attribute 'read'
```

**Comment by FrantisekPavlicek** [comment]
I checked again, but I don' have those in the plugin anymore. But if I remember correctly, the problem was solved by something related to Solr, either restarting Solr, or correctly adding the fields to the Solr schema. Sorry I can't help a bit more.
