### ISSUE TITLE
Install issue: PluginNotFoundException

### ISSUE THREAD

**Issue by keknight** [ckan/ckanext-scheming#202]
We’re trying to install the CKAN Scheming plugin on CKAN 2.8.1 using Docker, but are getting the “PluginNotFoundException” error. After hours of troubleshooting, we’re stuck. Could anyone offer advice on how to get this working?
 
We have:
 
Activated the virtual environment, installed the plugin via pip, and have run python setup.py develop
Ensured that the plugin name is in the setup.py file
Added plugin name (as it appears in the setup.py file) to the .ini file
ckan.plugins = stats text_view image_view recline_view datastore datapusher extrafields ornl_theme scheming_datasets

Our other plugins are working successfully, so we’re stuck as to why Scheming isn’t. We have not modified the plugin at all yet—this is as it currently is on Git.

**Comment by keknight** [comment]
So we figured it out: it was an issue with folder permissions. For some reason the plugin file was owned by root--changing the permission from root to ckan fixed it. This wasn't readily apparent.

**Comment by saikarthikp9** [comment]
I am seeing the same issue, but my folder permissions are good (owned by ckan). 

[https://github.com/ckan/ckanext-scheming/issues/334](issue)
