### ISSUE TITLE
Problem with CKAN API REST and custom fields.

### ISSUE THREAD

**Issue by manurodal** [ckan/ckanext-scheming#204]
I added to the ckan_dataset.json schema a new field for translate core fields (like title, description) with ckanext-fluent extension for this type of preset (fluent_core_translated). In the form of the package I can change title (for example) for the selected languages, but when I query this data from API REST, with the method package_search I do not have the translated_title, instead, in the method package_show I have this field with the correct translations. Someone know, how does i can activate this fields with the package_search method?

**Comment by metaodi** [comment]
@manurodal package_search uses Solr to return results, so in order to get a custom field in package_search you need to index that field (usually done in the before_index method of IPackageController) and add it to your Solr schema.

**Comment by manurodal** [comment]
@metaodi thanks for your answer. I defined a new field on solr's schema and indexed a field in IPackageController.before_index: 
`<field name="title_translated" type="string" indexed="true" stored="true" multiValued="true"/>`
and
`def before_index(self, pkg_dict):

        pkg_dict['title_translated'] = pkg_dict.get('title_translated');

        return pkg_dict
`
In package_show the new field seems like: 
`"title_translated": {
"gl": "Title in gl",
"es": "Title in es"
},`
But in package_search method I continue without this field, ¿do you know what I'm doing wrong?

Sorry for the inconvenience, I'm very noob on Solr.
Best regards.

**Comment by metaodi** [comment]
After changing the solr schema you need to restart solr, and after implementing before_index you need to [rebuild the solr index](https://docs.ckan.org/en/ckan-2.7.3/maintaining/paster.html#search-index-rebuild-search-index) for any of these changes to take effect.

After rebuilding the index, you can check directly on the solr admin web interface if the content of solr matches your expectations.

Hope this helps.

**Comment by manurodal** [comment]
@metaodi WORKS! Thank you! Rebuild the index was the step that I needed to complete the creation of new fields. You save my day, thanks a lot! 👍
