### ISSUE TITLE
template is not loading / rendering

### ISSUE THREAD

**Issue by HareRee** [ckan/ckanext-scheming#208]
I've installed the extension and set the schema to `scheming.dataset_schemas = ckanext.scheming:camel_photos.json` in my .ini file.  

However, when I goto add a dataset I'm seeing the default schema.  I'm also not seeing any errors in my httpd logs.    

I'm using the following to build my local environment: https://github.com/UtrechtUniversity/ilab-catalog

**Comment by wardi** [comment]
instead of /dataset/new try navigating to /camel-photos/new

**Comment by HareRee** [comment]
Thanks.
