### ISSUE TITLE
form-control class creates two inputs fields, one above the other

### ISSUE THREAD

**Issue by frafra** [ckan/ckanext-scheming#219]
Removing `form-control` fixes the issue:
https://github.com/ckan/ckanext-scheming/blob/1a096dd963424884bbaf70fa28da5c1de058d27d/ckanext/scheming/templates/scheming/form_snippets/multiple_select.html#L29

![Screenshot_2019-11-06 Datasets - COAT Data Portal](https://user-images.githubusercontent.com/4068/68318174-a3ca0980-00bc-11ea-879e-ad7c823c842e.png)

**Comment by frafra** [comment]
Same glitch happens for file format.

**Comment by howff** [comment]
Are you sure it's multiple_select.html which renders the tags(keywords) in your screenshot?
I see the same problem when using tags but multiple_select.html is not used, text.html is used.
However editing text.html to remove form-control affects all normal text entry fields.
The solution seems to be adding a new form_snippet, say tags.html, which is a copy of text.html but without the form-control class, and referencing this form_snippet in the preset.

(No comment on the file format issue, I've not tried it yet)

**Comment by frafra** [comment]
I found this problem in tags first, but I had to fix it on `text.html` too.

**Comment by bstutsky** [comment]
This also seems to be an issue for `resource_format_autocomplete`

**Comment by LukeTully** [comment]
@frafra What did your schema look like for this? Did you resolve the issue?

**Comment by frafra** [comment]
@LukeTully I just removed the class from the template manually as workaround.

**Comment by Patrick1Rhode** [comment]
Note guys, we also have experienced this issue.

![image_2021_04_16T16_08_44_961Z](https://user-images.githubusercontent.com/8822597/115056781-87eaaa00-9ee3-11eb-871a-f8ac56f9fa47.png)


We have solved this and other problems by adding a custom CSS.

.form-control {
    padding: unset;
}

.control-full input, .control-full select, .control-full textarea {
    height: 34px;
}

.select2-container{
    height:auto;
}

Can we evaluate this CSS in the core?

**Comment by frafra** [comment]
This bug has been fixed.
