### ISSUE TITLE
Simplest way to configure certain scheming fields so only "members" can see them?

### ISSUE THREAD

**Issue by ryangermann-gov-on-ca** [ckan/ckanext-scheming#257]
Our CKAN application is publicly accessible, but we have some fields related to the data that are only of interest to the data maintainers, and we want to not display those fields to the public.

Is there a way to configure scheming fields so the fields are only visible on the Dataset detail screen to "members" of that group or organization?

**Comment by wardi** [comment]
No, scheming doesn't help with hiding fields for some users.

You could customize the templates that display your datasets to add some kind of permissions check. Note that the fields will still be present in the JSON version of the dataset available through the API. If you want to hide the values there you might need to override the package_show and package_search actions. There may be some existing extensions that can help with hiding specific fields as well.
