### ISSUE TITLE
Technique for pre-filling default values in Scheming fields

### ISSUE THREAD

**Issue by ryangermann-gov-on-ca** [ckan/ckanext-scheming#258]
We have a few fields in our Scheming configuration that, 95 times out of 100, will have a "generic" value, but on occasion it would be necessary to create the Dataset with a different value for this field.

Is there a "best" way to set a default value? We have the field set up with a form_placeholder but of course that provides a guide for the user as to what to key in, but isn't stored as the vaule... so is there a "best" way to elevate the Placeholder value to the default value?

**Comment by wardi** [comment]
the dataset form supports GET parameters to populate field values e.g. `/dataset/new?notes=some_default_notes&…` so the user doesn't have to fill them out, does this work for you?

If not, the "composite" branch I'm working on right now includes field `default` in the schema. You can even populate a `default_jinja2` a jinja2 expression so you can call helpers etc. No ETA on merging this branch to master yet.

**Comment by ryangermann-gov-on-ca** [comment]
This sounds like it could work... we could just add to the "Add Dataset" button the extra params for the fields we'd want to have default values... not sure how easy to alter that will be in the 'Forms" page where it appears, but sounds easy enough :-)  Thanks!
