### ISSUE TITLE
Use ckan_extends?

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckanext-scheming#262]
Currently, ckanext-scheming's templates does not use `ckan_extends`.  

This makes it hard to tweak UI and functional elements to select templates without totally overriding scheming's templates and having to snapshot/copy functionality from the overridden scheming template or subclassing the SchemingDatasets plugin (#138).

Is there a specific reason why ckanext-scheming cannot use `ckan_extends`?

**Comment by wardi** [comment]
I was just trying to keep things simple. Not against adding ckan_extends where it makes sense.
