### ISSUE TITLE
multiple_select selects extra elements

### ISSUE THREAD

**Issue by frafra** [ckan/ckanext-scheming#268]
If a multiple choices allows both "world" and "hello world" as values, and the multiple choice contains "hello world", also "hello" is displayed.

https://github.com/ckan/ckanext-scheming/blob/367d50f00492de757a6acec30d3641e437ba2b74/ckanext/scheming/templates/scheming/display_snippets/multiple_choice.html#L5

Possible fix:

```
{%- set values = data[field.field_name].split(',') -%}
{%- set labels = [] -%}

{%- for choice in h.scheming_field_choices(field) -%}
    {%- for value in values -%}
        {%- if choice.value == value -%}
          {%- do labels.append(h.scheming_language_text(choice.label)) -%}
        {%- endif -%}
    {%- endfor -%}
{%- endfor -%}
```

**Comment by wardi** [comment]
makes sense. care to create a PR?

**Comment by frafra** [comment]
Ok, I think I pinpointed the issue.
`scheming_multiple_choice_output` is the correct validator to put in place, but there is a problem when loading the data again.
```
{{"selected " if val in data[field.field_name] }}
```
This should probably look like this:
```
{{"selected " if val in data.get(field.field_name, '').split(',') 
```

**Comment by wardi** [comment]
when you use `scheming_multiple_choice_output` doesn't `data[field.field_name]` become a list of strings?

**Comment by frafra** [comment]
Not really, as `data[field.field_name]` is loaded as a string.
`multiple_choice.html` shows it like: `'{a,b,"c d"}'`, so `if choice.value in values` selects wrong values (if `choice.value` is `c`, then `c d` gets listed too).
This is happening Solr 6 and CKAN 2.8 / 2.9.

**Comment by frafra** [comment]
Ok, I got it. My fault.
```
      "validators": "scheming_multiple_choice",
      "output_validators": "scheming_multiple_choice_output",
```

This works, and it is how `preset.json` is set. I just needed to add a validator in both cases for backward compatibility and some custom functions *before* `scheming_multiple_choice` and *after* `scheming_multiple_choice_output`.

Thank you for your support! :)
