### ISSUE TITLE
Enhancement: Have ability to add additional choices to scheming_datastore_choices helper

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckanext-scheming#270]
Oftentimes, the reference tables that can be used for `scheming_datastore_choices` do not have all the values required to fulfill business requirements.

Common values like "N/A", "None", "Pending", etc.

It would be awesome if `scheming_datastore_choices` can have an additional parameter called "additional_choices":

```
{
  "preset": "select",
  "choices_helper": "scheming_datastore_choices",
  "datastore_choices_resource": "countries-resource-id-or-alias",
  "datastore_choices_columns": {
    "value": "Country Code",
    "label": "English Country Name"
  },
 "additional_choices": [
    {
      "value": "na",
      "label": "N/A"
    },
    {
      "value": "none",
      "label": "None"
    },
    {
      "value": "pending",
      "label": "Pending"
    },
  ],
}
```

**Comment by wardi** [comment]
I like this idea. Should be a simple PR if you have the time.
