### ISSUE TITLE
Incorrect (?) installation instructions

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckanext-scheming#274]
The installation instructions (https://github.com/ckan/ckanext-scheming#installation) tell you to run

```
pip install -r ckanext-scheming/requirements.txt
```

but there is no `requirements.txt` file 

```
(default) ckan@ckan:/usr/lib/ckan/default/src/ckanext-scheming$ ls
CHANGELOG.md  COPYING.fr   README.md  ckanext_scheming.egg-info  setup.py               test.ini
COPYING       MANIFEST.in  ckanext    setup.cfg                  test-requirements.txt  test_subclass.ini
```

Is running `python setup.py develop` the equivalent?

**Comment by mabah-mst** [comment]
I just discovered the same issue as I have a build script pinned to building from commit https://github.com/ckan/ckanext-scheming/tree/c968dd09f16bd9e1d179c137d303cda52cc67dc3 which incidentally seems to be the last version with a requirements.txt . When trying to move my "pinned commit id" to the latest commit id, it fails on the absence of the requirements.txt file.

**Comment by wardi** [comment]
readme updated https://github.com/ckan/ckanext-scheming/commit/8ac2a6a9cecc1792cfc55fd46bfcea4db4bc2300 . thanks!

**Comment by mabah-mst** [comment]
Verified
