### ISSUE TITLE
menu item cannot be found for custom types

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckanext-scheming#277]
In CKAN 2.8 (with pylons), `scheming` automagically dealt with routing for custom types; e.g. 

```
{
  "scheming_version": 1,
  "organization_type": "publisher",
   [...]
}
```

would allow us to use the change the site nav:

```
          {% block header_site_navigation_tabs %}
              {{ h.build_nav_main( 
                  ('search', _('Datasets')), 
                  ('publisher_index', _('Publishers')), 
                  ('home.about', _('About')) ) }}
          {% endblock %}
``` 

in 2.9, after installing scheming and exposing the custom schema, using either `publisher_index` or `publisher.index` (to reflect the flask notation) results in:

```
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/lib/helpers.py", line 1113, in _make_menu_item
    raise Exception('menu item `%s` cannot be found' % menu_item)
Exception: menu item `publisher.index` cannot be found
```

(or `publisher_index`).

Do I need to expose the routes myself now?

**Comment by wardi** [comment]
It looks like the names for the urls registered as blueprints for IDatasetForm plugins have changed a bit: https://github.com/ckan/ckan/blob/0e21a4e9eafc638dedfd9ed1106e9303ed8b123e/ckan/lib/plugins.py#L144

Try `'publisher'` instead of `'publisher.index'`. Maybe @smotornyuk knows more about this change.

**Comment by wood-chris** [comment]
Hmm, that doesn't work either I'm afraid:

```
  File "/home/ckan/ckan/lib/default/src/ckan/ckan/lib/helpers.py", line 1113, in _make_menu_item
    raise Exception('menu item `%s` cannot be found' % menu_item)
Exception: menu item `publishers` cannot be found
```

**Comment by wood-chris** [comment]
Hmm, sorry! There must have been a typo somewhere. I've gone through the motions again (while trying something else) and it does seem to work now.
