### ISSUE TITLE
display_property key not listed in docs

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckanext-scheming#280]
`display_property` isn't listed as an option in the list of fields: https://github.com/ckan/ckanext-scheming#field-keys but is used in examples, e.g. https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/ckan_dataset.yaml#L41

It would be useful to know the scope / range / etc of this field

**Comment by wardi** [comment]
fixed by 540bce0
