### ISSUE TITLE
Should multiple_text items respect help_text and form_placeholder correctly?

### ISSUE THREAD

**Issue by wood-chris** [ckan/ckanext-scheming#283]
1. text input for `multiple_text` fields don't show `form_placeholder` text (perhaps this is by design?)
2. `help_text` is duplicated when the `multiple_text` preset is used
3. maybe related, setting `help_inline` to `true` or `false` makes no difference 

![Screenshot 2021-03-08 at 18 32 22](https://user-images.githubusercontent.com/10977677/110365530-0c245480-803d-11eb-9973-cf46b2492789.png)

**Comment by ccancellieri** [comment]
this should be addressed by last commit, can you please verify?

**Comment by kdwarn** [comment]
I can verify that updating the install eliminates the duplicated help text.
