### ISSUE TITLE
Form is not being updated for datasets

### ISSUE THREAD

**Issue by ddazal** [ckan/ckanext-scheming#321]
Hi, I have installed CKAN 2.9.5 (last version) from package on Ubuntu 20.04 and this extension without any issue. However, when I set the `scheming.dataset_schemas` option in the config file the changes are not reflected on the dataset form creation.

My ckan.ini:
```
ckan.plugins = stats text_view image_view recline_view datastore scheming_datasets scheming_groups
scheming.dataset_schemas = ckanext.scheming:camel_photos.yaml
scheming.group_schemas = ckanext.scheming:group_with_bookface.json
```
Note that I'm also using the `scheming.group_schemas`. In this case the group form is updated successfully (see image) while the dataset form is still the default

![WhatsApp Image 2022-03-17 at 6 51 52 PM](https://user-images.githubusercontent.com/21014225/158912303-fa53c3f1-71d3-452b-848a-84c3825e63fb.jpeg)

When I call `/api/3/action/scheming_dataset_schema_list` I get the following response:

```
{
    "help": "http://localhost/api/3/action/help_show?name=scheming_dataset_scheming_list",
    "success": true,
    "result": ["camel-photos"]
}
```
**Am I missing a particular step in the configuration?**

_How did I install this extension?_
```
$ cd /usr/lib/ckan/default/src
$ sudo su
$ . /usr/lib/ckan/default/bin/activate
(default) $ pip install -e "git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming"
```

**Comment by AlasdairGray** [comment]
I am seeing the same behaviour using CKAN-Docker with 2.10.1. Is there any solution to this?

**Comment by wardi** [comment]
Dataset types are made available at different urls, e.g. `/camel-photos/new` for new "camel-photos"-type datasets

**Comment by AlasdairGray** [comment]
Ah, thanks for that. I see that is mentioned in the [dataset_type](https://github.com/ckan/ckanext-scheming#dataset_type) section of the readme, but not up in the [Example Schemas](https://github.com/ckan/ckanext-scheming#configuration) section that appears earlier in the README. It would be helpful to have details of the different routes earlier.

**Comment by wardi** [comment]
good idea, would you care to open a pull request with a fix for the readme?
