### ISSUE TITLE
PluginNotFoundException scheming_datasets

### ISSUE THREAD

**Issue by saikarthikp9** [ckan/ckanext-scheming#334]
Environment: Kubernetes/Docker
CKAN Version: 2.9

Folder Structure:
/srv/app/src/ckan/
/srv/app/src/ckanext-scheming/

Able to install fine but on container run, I see following error:
![Screen Shot 2022-06-12 at 5 31 42 AM](https://user-images.githubusercontent.com/69390532/173229140-548fd9a6-e1fb-451b-87a2-779494f2d059.png)

**Comment by wardi** [comment]
What Kubernetes/Docker configuration are you using? I need more information to reproduce your issue.

**Comment by saikarthikp9** [comment]
AWS EKS 
Kubernetes version: 1.20

Have a working version without ckanext-scheming package

Helm chart and docker image similar to:
https://github.com/keitaroinc/ckan-helm

**Comment by saikarthikp9** [comment]
Solved.

I am using wheels. So I had to pip install ckanext-scheming after.
`RUN pip wheel --wheel-dir=/wheels git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming`
