### ISSUE TITLE
Feature Request: Setting Disabled Default  value in select field

### ISSUE THREAD

**Issue by hussnainwithss** [ckan/ckanext-scheming#336]
In the current select field, there is no disabled default value prompt such as 'Please select an option' which normal select fields usually have. Instead i think the first value in the list of options is set as selected by default which can be problematic when you want the user to select an option on a mandatory field but they can skip right ahead without selecting any value.  Is there any way to get this behavior. if not maybe it can be added as a new feature.

**Comment by wardi** [comment]
You might be looking for `form_include_blank_choice` https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/form_snippets/select.html#L6
If you set this to `True` in your schema then select boxes will include a blank (invalid) choice at the top, forcing users to choose an option before submitting.

**Comment by hussnainwithss** [comment]
@wardi thanks for the help. solved now.

**Comment by wardi** [comment]
@hussnainwithss 899a3bc
