### ISSUE TITLE
Cannot create custom datasets after form pages feature

### ISSUE THREAD

**Issue by mmeisel** [ckan/ckanext-scheming#350]
Hello, I have a CKAN site that's using this (excellent) extension to create a custom dataset type, let's call it mydataset. Prior to the form pages feature, the typical flow when creating a new dataset was always: "(1) Create dataset" followed by "(2) Add data". This was working just fine for mydatasets as well prior to the merge of #346.

After the merge of #346, without changing anything else, when I fill out the "Create dataset" form and click "Next: Add Data", I am sent to `/mydataset/new/new-dataset-name/2`, which is a 404. The previous behavior was to go to `/mydataset/new-dataset-name/resource/new` to add data.

As a result, I can't actually create any mydatasets after this change.

I'm using CKAN 2.9.

**Comment by wardi** [comment]
Thanks @mmeisel I'll take a look

**Comment by wardi** [comment]
https://github.com/ckan/ckanext-scheming/commit/72b9aa6d13e75d1e037cef987df09d8c2ecfeb11 should fix this issue

**Comment by mmeisel** [comment]
Indeed it did, thanks for the quick turnaround, @wardi!
