### ISSUE TITLE
mounting the ini file changes to docker image

### ISSUE THREAD

**Issue by JackBurns1984** [ckan/ckanext-scheming#355]
Hi, 
 installing this extension on ubuntu has been great, but I cant get it to work through docker. 

I have update the .env file with the plugin + custom lines scheming.dataset_schemas etc,  but the custom lines dont pull through to the ckan.ini file, the plugin does though. 

any advise on how to get this working on a docker build? thanks

**Comment by mjanez** [comment]
There are several options, depending on how you start CKAN with Docker. 

1. In theory, [ckanext-envvars](https://github.com/okfn/ckanext-envvars#ckanext-envvars) detects non-standard variables.
    >For keys that don't normally begin with 'CKAN', add 'CKAN___' (3 underscores) to the beginning to help the extension identify these keys, e.g.:
    >```ini
    >sqlalchemy.url --> CKAN___SQLALCHEMY__URL
    >beaker.session.secret --> CKAN___BEAKER__SESSION__SECRET
    >
    >#i.e.
    >scheming.dataset_schemas --> CKAN___SCHEMING__DATASET_SCHEMAS
    >```

2. If that doesn't work, [we have implemented a script](https://github.com/mjanez/ckan-docker/blob/master/ckan/docker-entrypoint.d/02_setup_scheming.sh) in ckan `docker-entrypoint.sh` that updates the variables defined in the `.env` (right after the main initialisation script (prerun.py) is run).
    ```bash
    #!/bin/bash
  
    # Update ckanext-scheming settings defined in the env var
    echo "Loading ckanext-scheming settings into ckan.ini"
    ckan config-tool $CKAN_INI \
        "scheming.dataset_schemas=$SCHEMA_CKANEXT_SCHEMING_DATASET_SCHEMA" \
        "scheming.group_schemas=$SCHEMA_CKANEXT_SCHEMING_GROUP_SCHEMAS" \
        "scheming.organization_schemas=$SCHEMA_CKANEXT_SCHEMING_ORGANIZATION_SCHEMAS" \
        "scheming.presets=$SCHEMA_CKANEXT_SCHEMING_PRESETS"
    ```

    Remember to include all scripts in the Dockerfile. `COPY docker-entrypoint.d/* /docker-entrypoint.d/`


    As mentioned in the [ckan-docker](https://github.com/ckan/ckan-docker/blob/cf4eef6111b95d8df6f91f4ab64fefb34467e5f9/README.md?plain=1#L126-L163) documentation:
    >To perform extra initialization steps you can add scripts to your custom images and copy them to the /docker-entrypoint.d folder (The folder should be created for you when you build the image). Any *.sh and *.py file in that folder will be executed just after the main initialization script (prerun.py) is executed and just before the web server and supervisor processes are started.
...
    > _[ckan/ckan-docker info](https://github.com/ckan/ckan-docker#6-extending-the-base-images)_

**Comment by wardi** [comment]
ckanext-scheming and ckanext-envvars interact in kind of a strange way. Try moving envvars before or after the scheming plugin(s) depending on if your ckan version has: https://github.com/ckan/ckan/pull/7033
