### ISSUE TITLE
Missing 3.0.0 tag 

### ISSUE THREAD

**Issue by davidlesieur** [ckan/ckanext-scheming#357]
When installing `ckanext-scheming`, I found strange that pip reported it as version 2.1.0 when I was expecting 3.0.0. It looks like the 3.0.0 tag is not actually attached to a branch of this repository (GitHub [also reports this](https://github.com/ckan/ckanext-scheming/commit/8d62a28370c4f231dbf2f9688ede93a0356410e3)).

**Comment by wardi** [comment]
@davidlesieur thanks, I forgot to push the release commit to master.
