### ISSUE TITLE
Can't use choices_helper for a required field

### ISSUE THREAD

**Issue by nwespe** [ckan/ckanext-scheming#390]
I've run into a problem trying to use a choices_helper (the scheming_datastore_choices) for a required field. In my understanding, the choices for the field are not populated until the datastore_choices_resource is added. However, I can't create a dataset to add the resource without filling out the field. Therefore I can't create any datasets.
Here is the information I've put in the yaml file:

- field_name: research_group
  label: Research Group
  required: true
  preset: select
  choices_helper: scheming_datastore_choices
  datastore_choices_resource: research_groups
  datastore_additional_choices:
  - value: na
    label: Not Applicable

When I try to add a dataset on the site, there are no dropdown options to select for Research Group. I've tried creating the dataset using the API with research_group="na" and get the following error: 
ValidationError: {'research_group': ['unexpected choice "na"'], '__type': 'Validation Error'}

Is this an unfortunate circular dependency? Would there be a way to work around this, at least for sysadmin users through the API?

**Comment by wardi** [comment]
You could set it to not required to create the one dataset you need, then change it back. Or you could use a different dataset schema for the dataset that contains the controlled lists

**Comment by wardi** [comment]
Maybe you want to create a new validator "required_if_not_sysadmin" kind of like https://github.com/ckan/ckan/blob/07a4b360471d29ab8d3b7de4e25dfd8a0fa6462c/ckan/logic/validators.py#L952-L963 and use that instead of the scheming_required validator

**Comment by nwespe** [comment]
Thanks for your responses. I decided to put all of the choices in the yaml file directly instead of using the choices_helper.
