### ISSUE TITLE
Rendered `select` elements on form do not have "dropdown" arrow

### ISSUE THREAD

**Issue by themowski** [ckan/ckanext-scheming#398]
### Overview

When a `select` element is rendered on the dataset create/edit form, it does not have the "dropdown arrow" that a user would expect to see on a `select` element. This makes the `select` look like an `input`, which is unintuitive.

After investigating, it appears that these elements have the `form-control` class applied, but not the `form-select` class. The latter seems to be what turns on the arrow, but I'm not 100% sure *why* that is the case -- looking at CKAN's CSS file, `form-select` also has `appearance: none` set, but in testing, adding the class fixed the issue.

### Example

Current behavior, using the "Visibility" selector:

![image](https://github.com/ckan/ckanext-scheming/assets/13295249/a156f1b9-4c4c-4226-9659-a16c452d46b8)

Adding the `form-select` class to this element, we get the following. Notice the arrow on the right side, which visually indicates that this is a select:

![image](https://github.com/ckan/ckanext-scheming/assets/13295249/41318bea-5ce7-4c0b-af8d-db62fadfc5c7)

### Suggested fix

I think that all we have to do is add `form-select` into the CSS "class" argument that is injected via `attrs` when `form.select()` is called in the form templates. I did a search for uses of `form.select` and came up with the following.

The main source is [`form_snippets/select.html`](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/form_snippets/select.html):

```diff
diff --git a/ckanext-scheming/ckanext/scheming/templates/scheming/form_snippets/select.html b/ckanext-scheming/ckanext/scheming/templates/scheming/form_snippets/select.html
index 1098d83..de889c2 100644
--- a/ckanext-scheming/ckanext/scheming/templates/scheming/form_snippets/select.html
+++ b/ckanext-scheming/ckanext/scheming/templates/scheming/form_snippets/select.html
@@ -30,7 +30,7 @@
     selected=option_selected,
     error=errors[field.field_name],
     classes=field.classes if 'classes' in field else ['control-medium'],
-    attrs=dict({"class": "form-control"}, **(field.get('form_attrs', {}))),
+    attrs=dict({"class": "form-control form-select"}, **(field.get('form_attrs', {}))),
     is_required=h.scheming_field_required(field)
     )
 %}
```

The "Visibility" selector from the screenshots is defined separately, in the [`form_snippets/organization.html`](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/form_snippets/organization.html) file.

The [`form_snippets/license.html`](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/form_snippets/license.html) file uses a different type of dropdown selector, so I think there's no change needed there.

The last occurrence is in [`form_snippets/datetime_tz.html`](https://github.com/ckan/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/form_snippets/datetime_tz.html).

If this looks correct & comprehensive, I can get a quick PR together.

**Comment by wardi** [comment]
Makes sense to me
