### ISSUE TITLE
Install Error: Error processing line 1

### ISSUE THREAD

**Issue by dkczk** [ckan/ckanext-scheming#402]
Hey guys,

I wanted to install scheming to make my life a bit easier when customising metadata fields. However, when installing scheming I get the following error:

> Error processing line 1 of /usr/local/lib/python3.8/dist-packages/ckanext-scheming-nspkg.pth:
> 
>   Traceback (most recent call last):
>     File "/usr/lib/python3.8/site.py", line 175, in addpackage
>       exec(line)
>     File "<string>", line 1, in <module>
>     File "<frozen importlib._bootstrap>", line 553, in module_from_spec
>   AttributeError: 'NoneType' object has no attribute 'loader'
> 
> Remainder of file ignored
> Obtaining ckanext-scheming from git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming
>   Cloning https://github.com/ckan/ckanext-scheming.git to ./src/ckanext-scheming
>   Running command git clone -q https://github.com/ckan/ckanext-scheming.git /usr/lib/ckan/default/src/ckanext-scheming
> Requirement already satisfied: ckanapi in /usr/local/lib/python3.8/dist-packages (from ckanext-scheming) (4.7)
> Requirement already satisfied: ckantoolkit>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from ckanext-scheming) (0.0.7)
> Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from ckanext-scheming) (2023.3.post1)
> Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from ckanext-scheming) (5.3.1)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from ckanext-scheming) (1.14.0)
> Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from ckanapi->ckanext-scheming) (45.2.0)
> Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from ckanapi->ckanext-scheming) (2.22.0)
> Requirement already satisfied: docopt in /usr/local/lib/python3.8/dist-packages (from ckanapi->ckanext-scheming) (0.6.2)
> Requirement already satisfied: python-slugify>=1.0 in /usr/local/lib/python3.8/dist-packages (from ckanapi->ckanext-scheming) (8.0.1)
> Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify>=1.0->ckanapi->ckanext-scheming) (1.3)
> Installing collected packages: ckanext-scheming
>   Running setup.py develop for ckanext-scheming
> Successfully installed ckanext-scheming

The weird thing is, that it concludes with "Successfully installed ckanext-scheming" and there is in fact a ckanext-scheming folder inside /usr/lib/ckan/default/src but shouldn't this folder be inside /usr/lib/ckan/default/src/ckan with the ckan-scheming extensions inside the /usr/lib/ckan/default/src/ckan/ckanext folder?

I did:

```
$ . /usr/lib/ckan/default/bin/activate
$ cd ..
$ cd src
$ sudo pip install -e "git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming"
``` 
(pip call without sudo resulted in an error telling me, that I don't have the required permissions)

System:
- Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-169-generic x86_64)
- ckan 2.9
- nginx 1.18.0
- Solr 9.4.1

Thanks in advance for your help!

**Comment by wardi** [comment]
I usually install with `git clone` and then `python setup.py develop` in the cloned directory. Does that work for you?

**Comment by wardi** [comment]
not sure why you had problems with pip, but if you figure it out please submit a PR.
